---
kind: pipeline
type: docker
name: default

steps:
- name: symfony
  image: composer
  commands: 
#  - composer install
#  - ping6 -c 1 ipv6.google.com
  - ping -c 1 google.com

- name: send telegram notification
  image: appleboy/drone-telegram
    settings:
      token: 
	from_secret: tocken
      to:
	from_secret: chatid
      message: >
        {{#success build.status}} 
         build {{build.number}} succeeded. Good job.
        {{else}}
         build {{build.number}} failed. Fix me please.
        {{/success}}
